-- Verify ALL staging table schemas

USE MarryBrown_DW;
GO

PRINT '=== staging_sales ===';
SELECT COLUMN_NAME, DATA_TYPE, CHARACTER_MAXIMUM_LENGTH
FROM INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_NAME = 'staging_sales' AND TABLE_SCHEMA = 'dbo'
ORDER BY ORDINAL_POSITION;
GO

PRINT '';
PRINT '=== staging_sales_items ===';
SELECT COLUMN_NAME, DATA_TYPE, CHARACTER_MAXIMUM_LENGTH
FROM INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_NAME = 'staging_sales_items' AND TABLE_SCHEMA = 'dbo'
ORDER BY ORDINAL_POSITION;
GO

PRINT '';
PRINT '=== staging_payments ===';
SELECT COLUMN_NAME, DATA_TYPE, CHARACTER_MAXIMUM_LENGTH
FROM INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_NAME = 'staging_payments' AND TABLE_SCHEMA = 'dbo'
ORDER BY ORDINAL_POSITION;
GO

PRINT '';
PRINT '=== Columns < 50 chars in ALL staging tables ===';
SELECT 
    TABLE_NAME,
    COLUMN_NAME,
    DATA_TYPE,
    CHARACTER_MAXIMUM_LENGTH
FROM INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_SCHEMA = 'dbo'
    AND TABLE_NAME LIKE 'staging_%'
    AND CHARACTER_MAXIMUM_LENGTH < 50
    AND CHARACTER_MAXIMUM_LENGTH IS NOT NULL
ORDER BY TABLE_NAME, CHARACTER_MAXIMUM_LENGTH;
GO

