PRINT 'Creating replica tables';

IF OBJECT_ID('dbo.com_5013_APP_4_SALES', 'U') IS NULL
BEGIN
    CREATE TABLE dbo.com_5013_APP_4_SALES (
        ID BIGINT NOT NULL,
        SALES_NO VARCHAR(50) NOT NULL,
        DATETIME__SALES_DATE DATE NULL,
        NOW_TIME VARCHAR(50) NULL,
        SALE_LOCATION VARCHAR(255) NULL,
        CUSTOMER_ID VARCHAR(255) NULL,
        CASHIER VARCHAR(255) NULL,
        SALES_PERSON VARCHAR(255) NULL,
        SALES_PERSON_USERNAME VARCHAR(255) NULL,
        SALES_TYPE VARCHAR(100) NULL,
        SUBSALES_TYPE VARCHAR(100) NULL,
        ORDER_SOURCE VARCHAR(100) NULL,
        DOUBLE_TOTAL_AMOUNT DECIMAL(18, 4) NULL,
        DOUBLE_TOTAL_TAX_AMOUNT DECIMAL(18, 4) NULL,
        DOUBLE_TOTAL_BILL_DISCOUNT_AMOUNT DECIMAL(18, 4) NULL,
        STRING_EXTEND_3 VARCHAR(255) NULL,
        SALES_STATUS VARCHAR(50) NULL,
        BATCHID VARCHAR(255) NULL,
        DATETIME__BUSINESS_DATE DATE NULL,
        NOW_DATETIME DATETIME NULL,
        UPDATE_TIMESTAMP ROWVERSION
        PRIMARY KEY (ID)
    );
END
GO

IF OBJECT_ID('dbo.com_5013_APP_4_SALESITEM', 'U') IS NULL
BEGIN
    CREATE TABLE dbo.com_5013_APP_4_SALESITEM (
        ID BIGINT NOT NULL,
        SALES_NO VARCHAR(50) NOT NULL,
        ITEM_CODE VARCHAR(255) NULL,
        ITEM_NAME VARCHAR(255) NULL,
        CATEGORY VARCHAR(255) NULL,
        INT_QUANTITY DECIMAL(18, 4) NULL,
        DOUBLE_PRICE DECIMAL(18, 4) NULL,
        DOUBLE_TOTAL_DISCOUNT_AMOUNT DECIMAL(18, 4) NULL,
        DOUBLE_MGST_TAX_AMOUNT DECIMAL(18, 4) NULL,
        DOUBLE_TOTAL_TAX_AMOUNT DECIMAL(18, 4) NULL,
        DOUBLE_SUB_TOTAL DECIMAL(18, 4) NULL,
        DOUBLE_COST DECIMAL(18, 4) NULL,
        VOUCHER_NO VARCHAR(255) NULL,
        SALES_TYPE VARCHAR(100) NULL,
        SUBSALES_TYPE VARCHAR(100) NULL,
        DATETIME__SALES_DATE DATE NULL,
        TAXCODE VARCHAR(50) NULL,
        MODEL VARCHAR(255) NULL,
        WBDELETED TINYINT NULL,
        UPDATE_TIMESTAMP ROWVERSION
        PRIMARY KEY (ID)
    );
END
GO

IF OBJECT_ID('dbo.com_5013_APP_4_PAYMENT', 'U') IS NULL
BEGIN
    CREATE TABLE dbo.com_5013_APP_4_PAYMENT (
        ID BIGINT NOT NULL,
        INVOICE_ID VARCHAR(50) NOT NULL,
        METHOD VARCHAR(50) NULL,
        DOUBLE_AMOUNT DECIMAL(18, 4) NULL,
        STRING_EXTEND_2 VARCHAR(255) NULL,
        DATETIME__DATE DATE NULL,
        PAYMENTDATETIME DATETIME NULL,
        TENDERAMOUNT DECIMAL(18, 4) NULL,
        CHANGEAMOUNT DECIMAL(18, 4) NULL,
        EODSESSIONID VARCHAR(255) NULL,
        ISVOID TINYINT NULL,
        UPDATE_TIMESTAMP ROWVERSION,
        PRIMARY KEY (ID)
    );
END
GO

IF OBJECT_ID('dbo.com_5013_APP_4_ITEM', 'U') IS NULL
BEGIN
    CREATE TABLE dbo.com_5013_APP_4_ITEM (
        ID BIGINT NOT NULL,
        ITEM_CODE VARCHAR(255) NULL,
        ATLTERNATE_LOOK_UP VARCHAR(255) NULL,
        ITEM_NAME VARCHAR(255) NULL,
        CATEGORY VARCHAR(255) NULL,
        ITEM_TYPE VARCHAR(255) NULL,
        ITEM_BRAND VARCHAR(255) NULL,
        DOUBLE_SALE_PRICE DECIMAL(18, 4) NULL,
        BOOL_DISABLED TINYINT NULL,
        BOOL_ISPACKAGE TINYINT NULL,
        ADDITIONAL_ITEM_TYPE VARCHAR(255) NULL,
        UPDATE_TIMESTAMP ROWVERSION,
        PRIMARY KEY (ID)
    );
END
GO

IF OBJECT_ID('dbo.com_5013_APP_4_CUSTOMER', 'U') IS NULL
BEGIN
    CREATE TABLE dbo.com_5013_APP_4_CUSTOMER (
        ID BIGINT NOT NULL,
        CUSTOMER_CODE VARCHAR(255) NULL,
        FIRST_NAME VARCHAR(255) NULL,
        LAST_NAME VARCHAR(255) NULL,
        COMPANY_NAME VARCHAR(255) NULL,
        MOBILE VARCHAR(100) NULL,
        EMAIL VARCHAR(255) NULL,
        CUSTOMER_GROUP VARCHAR(255) NULL,
        DOUBLE_ACCUMULATE_VALUE DECIMAL(18, 4) NULL,
        DOUBLE_POINT_VALUE DECIMAL(18, 4) NULL,
        BOOL_ACTIVE TINYINT NULL,
        DATETIME__CREATION_DATE DATETIME NULL,
        DATETIME__DOB DATETIME NULL,
        UPDATE_TIMESTAMP ROWVERSION,
        PRIMARY KEY (ID)
    );
END
GO

IF OBJECT_ID('dbo.com_5013_LOCATION_DETAIL', 'U') IS NULL
BEGIN
    CREATE TABLE dbo.com_5013_LOCATION_DETAIL (
        LOCATION_INT_ID INT NOT NULL,
        ID VARCHAR(255) NOT NULL,
        LOCATIONNAME VARCHAR(255) NULL,
        LOCSTATUS VARCHAR(100) NULL,
        LOCATION_DELETED TINYINT NULL,
        ADDRESS1 VARCHAR(255) NULL,
        CITY VARCHAR(100) NULL,
        STATE VARCHAR(100) NULL,
        POSTCODE VARCHAR(20) NULL,
        UPDATE_TIMESTAMP ROWVERSION,
        PRIMARY KEY (LOCATION_INT_ID)
    );
END
GO

IF OBJECT_ID('dbo.com_5013_APP_4_VOUCHER_MASTER', 'U') IS NULL
BEGIN
    CREATE TABLE dbo.com_5013_APP_4_VOUCHER_MASTER (
        ID BIGINT NOT NULL,
        RULE_TITLE VARCHAR(255) NULL,
        RULE_DESCRIPTION VARCHAR(1000) NULL,
        REWARD_CODE VARCHAR(100) NULL,
        VOUCHER_MASTER_TYPE INT NULL,
        DATETIME__ACTIVATE_DATE DATETIME NULL,
        DATETIME__EXPIRY_DATE DATETIME NULL,
        IS_ACTIVATE TINYINT NULL,
        WBDELETED TINYINT NULL,
        UPDATE_TIMESTAMP ROWVERSION,
        PRIMARY KEY (ID)
    );
END
GO

IF OBJECT_ID('dbo.com_5013_APP_4_STAFF', 'U') IS NULL
BEGIN
    CREATE TABLE dbo.com_5013_APP_4_STAFF (
        ID BIGINT NOT NULL,
        STAFFUSERNAME VARCHAR(255) NULL,
        STAFFFULLNAME VARCHAR(255) NULL,
        STAFFTYPE VARCHAR(100) NULL,
        UPDATE_TIMESTAMP ROWVERSION,
        PRIMARY KEY (ID)
    );
END
GO

IF OBJECT_ID('dbo.com_5013_APP_4_CASHIER_DRAWER', 'U') IS NULL
BEGIN
    CREATE TABLE dbo.com_5013_APP_4_CASHIER_DRAWER (
        SITEID VARCHAR(255) NOT NULL,
        BRANCHID VARCHAR(255) NULL,
        TERMINALNAME VARCHAR(255) NULL,
        UPDATE_TIMESTAMP ROWVERSION,
        PRIMARY KEY (SITEID)
    );
END
GO

IF OBJECT_ID('dbo.com_5013_APP_4_VOIDSALESITEM', 'U') IS NULL
BEGIN
    CREATE TABLE dbo.com_5013_APP_4_VOIDSALESITEM (
        ID BIGINT NOT NULL,
        SALESITEM_ID BIGINT NULL,
        SALES_NO BIGINT NULL,
        VOID_PERSON VARCHAR(255) NULL,
        DATETIME__VOID_DATETIME DATE NULL,
        VOID_REASON VARCHAR(255) NULL,
        VOID_AMOUNT DECIMAL(18, 4) NULL,
        VOID_QUANTITY DECIMAL(18, 4) NULL,
        DOUBLE_COST DECIMAL(18, 4) NULL,
        PERFORMED_TYPE VARCHAR(100) NULL,
        UPDATE_TIMESTAMP ROWVERSION,
        PRIMARY KEY (ID)
    );
END
GO

IF OBJECT_ID('dbo.com_5013_APP_4_SALESCREDITNOTE', 'U') IS NULL
BEGIN
    CREATE TABLE dbo.com_5013_APP_4_SALESCREDITNOTE (
        ID BIGINT NOT NULL,
        REF_SALES_ID BIGINT NULL,
        CUSTOMER_ID BIGINT NULL,
        CUSTOMER_NAME VARCHAR(255) NULL,
        DOUBLE_TOTAL_AMOUNT DECIMAL(18, 4) NULL,
        DOUBLE_TOTAL_TAX_AMOUNT DECIMAL(18, 4) NULL,
        DOUBLE_TOTAL_BILL_DISCOUNT_AMOUNT DECIMAL(18, 4) NULL,
        ORDER_SOURCE VARCHAR(100) NULL,
        SALES_PERSON VARCHAR(255) NULL,
        SALES_PERSON_USERNAME VARCHAR(255) NULL,
        LOCATION_ID VARCHAR(255) NULL,
        STATUS VARCHAR(100) NULL,
        DATETIMEUTC_DATE DATETIME NULL,
        DATETIMEUTC_BUSINESS_DATE DATETIME NULL,
        UPDATE_TIMESTAMP ROWVERSION,
        PRIMARY KEY (ID)
    );
END
GO

IF OBJECT_ID('dbo.com_5013_APP_4_SALESCREDITNOTEITEM', 'U') IS NULL
BEGIN
    CREATE TABLE dbo.com_5013_APP_4_SALESCREDITNOTEITEM (
        ID BIGINT NOT NULL,
        DOCUMENT_ID BIGINT NULL,
        REF_SALESITEM_ID BIGINT NULL,
        ITEM_ID BIGINT NULL,
        ITEM_CODE VARCHAR(255) NULL,
        ITEM_NAME VARCHAR(255) NULL,
        DOUBLE_QUANTITY DECIMAL(18, 4) NULL,
        DOUBLE_SUB_TOTAL DECIMAL(18, 4) NULL,
        DOUBLE_TOTAL_TAX_AMOUNT DECIMAL(18, 4) NULL,
        SUBSALES_TYPE VARCHAR(100) NULL,
        VOUCHER_NO VARCHAR(255) NULL,
        UPDATE_TIMESTAMP ROWVERSION,
        PRIMARY KEY (ID)
    );
END
GO

IF OBJECT_ID('dbo.com_5013_APP_4_SALESDEBITNOTE', 'U') IS NULL
BEGIN
    CREATE TABLE dbo.com_5013_APP_4_SALESDEBITNOTE (
        ID BIGINT NOT NULL,
        REF_SALES_ID BIGINT NULL,
        CUSTOMER_ID BIGINT NULL,
        DOUBLE_TOTAL_AMOUNT DECIMAL(18, 4) NULL,
        DOUBLE_TOTAL_TAX_AMOUNT DECIMAL(18, 4) NULL,
        DOUBLE_TOTAL_BILL_DISCOUNT_AMOUNT DECIMAL(18, 4) NULL,
        ORDER_SOURCE VARCHAR(100) NULL,
        SALES_PERSON VARCHAR(255) NULL,
        SALES_PERSON_USERNAME VARCHAR(255) NULL,
        LOCATION_ID VARCHAR(255) NULL,
        STATUS VARCHAR(100) NULL,
        DATETIMEUTC_DATE DATETIME NULL,
        DATETIMEUTC_BUSINESS_DATE DATETIME NULL,
        UPDATE_TIMESTAMP ROWVERSION,
        PRIMARY KEY (ID)
    );
END
GO

IF OBJECT_ID('dbo.com_5013_APP_4_SALESDEBITNOTEITEM', 'U') IS NULL
BEGIN
    CREATE TABLE dbo.com_5013_APP_4_SALESDEBITNOTEITEM (
        ID BIGINT NOT NULL,
        DOCUMENT_ID BIGINT NULL,
        REF_SALESITEM_ID BIGINT NULL,
        ITEM_ID BIGINT NULL,
        ITEM_CODE VARCHAR(255) NULL,
        ITEM_NAME VARCHAR(255) NULL,
        DOUBLE_QUANTITY DECIMAL(18, 4) NULL,
        DOUBLE_SUB_TOTAL DECIMAL(18, 4) NULL,
        DOUBLE_TOTAL_TAX_AMOUNT DECIMAL(18, 4) NULL,
        SUBSALES_TYPE VARCHAR(100) NULL,
        VOUCHER_NO VARCHAR(255) NULL,
        UPDATE_TIMESTAMP ROWVERSION,
        PRIMARY KEY (ID)
    );
END
GO

IF OBJECT_ID('dbo.com_5013_APP_4_SALESDELIVERY', 'U') IS NULL
BEGIN
    CREATE TABLE dbo.com_5013_APP_4_SALESDELIVERY (
        ID BIGINT NOT NULL,
        SALES_NO VARCHAR(50) NULL,
        SALESITEM_ID VARCHAR(50) NULL,
        FROM_LOCATION VARCHAR(255) NULL,
        DELIVERY_STREET VARCHAR(255) NULL,
        DELIVERY_CITY VARCHAR(100) NULL,
        DELIVERY_STATE VARCHAR(100) NULL,
        DELIVERY_COUNTRY VARCHAR(100) NULL,
        DELIVERY_ZIPCODE VARCHAR(20) NULL,
        RECIPIENT VARCHAR(255) NULL,
        RECIPIENT_CONTACT VARCHAR(100) NULL,
        DELIVERY_METHOD VARCHAR(100) NULL,
        TRACKING_CODE VARCHAR(255) NULL,
        UPDATE_TIMESTAMP ROWVERSION,
        PRIMARY KEY (ID)
    );
END
GO

IF OBJECT_ID('dbo.com_5013_APP_4_EXTENDEDSALESITEM', 'U') IS NULL
BEGIN
    CREATE TABLE dbo.com_5013_APP_4_EXTENDEDSALESITEM (
        ID BIGINT NOT NULL,
        SALESITEM_ID BIGINT NULL,
        EPC VARCHAR(255) NULL,
        RFIDSERIALNUMBER INT NULL,
        UPDATE_TIMESTAMP ROWVERSION,
        PRIMARY KEY (ID)
    );
END
GO

IF OBJECT_ID('dbo.com_5013_APP_4_EPAYMENTLOG', 'U') IS NULL
BEGIN
    CREATE TABLE dbo.com_5013_APP_4_EPAYMENTLOG (
        ID BIGINT NOT NULL,
        SALESNUMBER VARCHAR(50) NULL,
        METHOD VARCHAR(50) NULL,
        STATUS VARCHAR(50) NULL,
        LOCATIONID VARCHAR(255) NULL,
        WALLETREFERENCEID VARCHAR(255) NULL,
        TYPE VARCHAR(50) NULL,
        AMOUNT DECIMAL(18, 4) NULL,
        TRANSACTIONDATETIME DATETIME NULL,
        ERRORMESSAGE VARCHAR(1000) NULL,
        UPDATE_TIMESTAMP ROWVERSION,
        PRIMARY KEY (ID)
    );
END
GO

IF OBJECT_ID('dbo.com_5013_APP_4_VOUCHER', 'U') IS NULL
BEGIN
    CREATE TABLE dbo.com_5013_APP_4_VOUCHER (
        ID BIGINT NOT NULL,
        VOUCHER_NO VARCHAR(255) NULL,
        SALES_ID BIGINT NULL,
        PAYMENT_ID BIGINT NULL,
        VOUCHER_DATE VARCHAR(50) NULL,
        DATETIME__VOUCHER_DATE DATE NULL,
        VOUCHER_EXPIRYDATE VARCHAR(50) NULL,
        DATETIME__VOUCHER_EXPIRYDATE DATE NULL,
        VOUCHER_TYPE VARCHAR(50) NULL,
        REDEMPTION_DATE VARCHAR(50) NULL,
        DATETIME__REDEMPTION_DATE DATE NULL,
        REDEMPTION_LOCATION VARCHAR(255) NULL,
        VOUCHER_VALUE DECIMAL(18, 4) NULL,
        VOUCHER_MASTER_ID BIGINT NULL,
        IS_API_VOUCHER TINYINT NULL,
        UPDATE_TIMESTAMP ROWVERSION,
        PRIMARY KEY (ID)
    );
END
GO

PRINT 'Replica tables ensured.';


