-- Migration: Create APP_4_EODLOG table for EOD session tracking
-- This table stores EOD session metadata including the business date
-- which determines how transactions are grouped in EOD reports

PRINT 'Creating APP_4_EODLOG table';
GO

IF OBJECT_ID('dbo.com_5013_APP_4_EODLOG', 'U') IS NULL
BEGIN
    CREATE TABLE dbo.com_5013_APP_4_EODLOG (
        ID BIGINT NOT NULL,
        LOCATIONID VARCHAR(255) NULL,
        SITEID VARCHAR(255) NULL,
        CASHIERDRAWERID VARCHAR(255) NULL,
        CASHIER VARCHAR(255) NULL,
        OPENINGDATETIME VARCHAR(25) NULL,
        CLOSINGDATETIME VARCHAR(25) NULL,
        OPENEDBY VARCHAR(255) NULL,
        CLOSEDBY VARCHAR(255) NULL,
        VERIFIEDBY VARCHAR(255) NULL,
        OPENINGDATE VARCHAR(25) NULL,
        OPENINGTIME VARCHAR(25) NULL,
        CLOSINGDATE VARCHAR(25) NULL,
        CLOSINGTIME VARCHAR(25) NULL,
        DATETIME__OPENINGDATETIME DATE NULL,
        DATETIME__CLOSINGDATETIME DATE NULL,
        DATETIME__OPENINGDATE DATE NULL,
        TIME__OPENINGTIME VARCHAR(14) NULL,
        DATETIME__CLOSINGDATE DATE NULL,
        TIME__CLOSINGTIME VARCHAR(14) NULL,
        BUSINESS_DATE VARCHAR(50) NULL,
        DATETIME__BUSINESS_DATE DATE NULL,
        INT_EXTEND_1 INT NULL,
        INT_EXTEND_2 INT NULL,
        INT_EXTEND_3 INT NULL,
        STRING_EXTEND_1 VARCHAR(255) NULL,
        STRING_EXTEND_2 VARCHAR(255) NULL,
        STRING_EXTEND_3 VARCHAR(255) NULL,
        WBDELETED TINYINT NULL,
        UPDATE_TIMESTAMP BINARY(8) NULL,
        ROWLOCKING VARCHAR(50) NULL,
        INT_RESET_COUNTER INT NULL,
        DOUBLE_PREVIOUS_ACCUMULATE_AMOUNT DECIMAL(16,4) NULL,
        DOUBLE_CURRENT_ACCUMULATE_AMOUNT DECIMAL(16,4) NULL,
        INT_PRINTCOUNT INT NULL,
        CONSTRAINT PK_com_5013_APP_4_EODLOG PRIMARY KEY CLUSTERED (ID)
    );
    PRINT 'Table dbo.com_5013_APP_4_EODLOG created.';
END
ELSE
BEGIN
    PRINT 'Table dbo.com_5013_APP_4_EODLOG already exists.';
END;
GO

-- Create index on DATETIME__BUSINESS_DATE for fast EOD session lookups
IF NOT EXISTS (SELECT * FROM sys.indexes WHERE name = 'IX_EODLOG_BusinessDate' AND object_id = OBJECT_ID('dbo.com_5013_APP_4_EODLOG'))
BEGIN
    CREATE NONCLUSTERED INDEX IX_EODLOG_BusinessDate
    ON dbo.com_5013_APP_4_EODLOG (DATETIME__BUSINESS_DATE)
    INCLUDE (LOCATIONID);
    PRINT 'Index IX_EODLOG_BusinessDate created.';
END;
GO

-- Create index on LOCATIONID for store-based lookups
IF NOT EXISTS (SELECT * FROM sys.indexes WHERE name = 'IX_EODLOG_LocationID' AND object_id = OBJECT_ID('dbo.com_5013_APP_4_EODLOG'))
BEGIN
    CREATE NONCLUSTERED INDEX IX_EODLOG_LocationID
    ON dbo.com_5013_APP_4_EODLOG (LOCATIONID);
    PRINT 'Index IX_EODLOG_LocationID created.';
END;
GO

PRINT 'APP_4_EODLOG migration complete.';
GO
