-- Migration: Create Product Mix source tables for pricing and cost replication
-- Tables: APP_4_PRODUCTMATRIX, APP_4_LOCATIONPRICE, APP_4_RECIPESUMMARY,
--         APP_4_SALESQUANTITIES, APP_4_COMBOITEMPRICE

PRINT 'Creating APP_4_PRODUCTMATRIX table';
GO

IF OBJECT_ID('dbo.com_5013_APP_4_PRODUCTMATRIX', 'U') IS NULL
BEGIN
    CREATE TABLE dbo.com_5013_APP_4_PRODUCTMATRIX (
        ID BIGINT NOT NULL,
        ITEMID VARCHAR(255) NULL,
        BARCODE VARCHAR(255) NULL,
        STOCKCODE VARCHAR(255) NULL,
        MANUFACTURER_CODE VARCHAR(255) NULL,
        LOCATION_ID VARCHAR(40) NULL,
        INSTORE_LOCATION VARCHAR(255) NULL,
        SET_1_VALUE VARCHAR(40) NULL,
        SET_2_VALUE VARCHAR(40) NULL,
        SET_3_VALUE VARCHAR(40) NULL,
        SET_4_VALUE VARCHAR(40) NULL,
        SET_5_VALUE VARCHAR(40) NULL,
        DOUBLE_QUANTITY DECIMAL(16,4) NULL,
        DATE_CREATED VARCHAR(255) NULL,
        TIME VARCHAR(255) NULL,
        DOUBLE_MANUFACTURER_SUGGESTED_RETAIL_PRICE DECIMAL(16,4) NULL,
        DOUBLE_SALE_PRICE DECIMAL(16,4) NULL,
        DOUBLE_EMPLOYEE_PRICE DECIMAL(16,4) NULL,
        DOUBLE_WHOLESALE_PRICE DECIMAL(16,4) NULL,
        DOUBLE_CUSTOM_PRICE DECIMAL(16,4) NULL,
        DOUBLE_WEB_PRICE DECIMAL(16,4) NULL,
        DOUBLE_WEB_DEALER_PRICE DECIMAL(16,4) NULL,
        DOUBLE_COST DECIMAL(16,4) NULL,
        DOUBLE_REORDER_POINT DECIMAL(16,4) NULL,
        DOUBLE_AVG_COST DECIMAL(16,4) NULL,
        DOUBLE_FIFO_COST DECIMAL(16,4) NULL,
        DOUBLE_LIFO_COST DECIMAL(16,4) NULL,
        DOUBLE_AVG_PROFIT DECIMAL(16,4) NULL,
        DOUBLE_FIFO_PROFIT DECIMAL(16,4) NULL,
        DOUBLE_LIFO_PROFIT DECIMAL(16,4) NULL,
        DOUBLE_LAST_STOCK_IN_COST DECIMAL(16,4) NULL,
        DATETIME__DATE_CREATED DATE NULL,
        TIME__TIME VARCHAR(14) NULL,
        INT_EXTEND_1 INT NULL,
        INT_EXTEND_2 INT NULL,
        INT_EXTEND_3 INT NULL,
        STRING_EXTEND_1 VARCHAR(255) NULL,
        STRING_EXTEND_2 VARCHAR(255) NULL,
        STRING_EXTEND_3 VARCHAR(255) NULL,
        BINARYKEY VARCHAR(255) NULL,
        WBDELETED TINYINT NULL,
        UPDATE_TIMESTAMP BINARY(8) NULL,
        PRICE_EXPIRY_DATE VARCHAR(25) NULL,
        DOUBLE_RESTRICTED_QUANTITY DECIMAL(16,4) NULL,
        CONSTRAINT PK_com_5013_APP_4_PRODUCTMATRIX PRIMARY KEY CLUSTERED (ID)
    );
    PRINT 'Table dbo.com_5013_APP_4_PRODUCTMATRIX created.';
END
ELSE
BEGIN
    PRINT 'Table dbo.com_5013_APP_4_PRODUCTMATRIX already exists.';
END;
GO

PRINT 'Creating APP_4_LOCATIONPRICE table';
GO

IF OBJECT_ID('dbo.com_5013_APP_4_LOCATIONPRICE', 'U') IS NULL
BEGIN
    CREATE TABLE dbo.com_5013_APP_4_LOCATIONPRICE (
        ID BIGINT NOT NULL,
        ITEM_ID VARCHAR(255) NULL,
        LOCATION_ID VARCHAR(255) NULL,
        DOUBLE_SALE_PRICE DECIMAL(16,4) NULL,
        DOUBLE_EMPLOYEE_PRICE DECIMAL(16,4) NULL,
        DOUBLE_WHOLESALE_PRICE DECIMAL(16,4) NULL,
        DOUBLE_CUSTOM_PRICE DECIMAL(16,4) NULL,
        DOUBLE_MANUFACTURER_SUGGESTED_RETAIL_PRICE DECIMAL(16,4) NULL,
        DOUBLE_WEB_PRICE DECIMAL(16,4) NULL,
        DOUBLE_WEB_DEALER_PRICE DECIMAL(16,4) NULL,
        DOUBLE_CUSTOM_COST DECIMAL(16,4) NULL,
        DOUBLE_MIN_PROFIT_MARGIN DECIMAL(16,4) NULL,
        INT_MARKDOWNCOUNT INT NULL,
        ROWLOCKING VARCHAR(25) NULL,
        INT_EXTEND_1 INT NULL,
        INT_EXTEND_2 INT NULL,
        INT_EXTEND_3 INT NULL,
        STRING_EXTEND_1 VARCHAR(255) NULL,
        STRING_EXTEND_2 VARCHAR(255) NULL,
        STRING_EXTEND_3 VARCHAR(255) NULL,
        WBDELETED TINYINT NULL,
        UPDATE_TIMESTAMP BINARY(8) NULL,
        PRICE_EXPIRY_DATE VARCHAR(25) NULL,
        DOUBLE_FOREIGN_COST DECIMAL(16,4) NULL,
        CONSTRAINT PK_com_5013_APP_4_LOCATIONPRICE PRIMARY KEY CLUSTERED (ID)
    );
    PRINT 'Table dbo.com_5013_APP_4_LOCATIONPRICE created.';
END
ELSE
BEGIN
    PRINT 'Table dbo.com_5013_APP_4_LOCATIONPRICE already exists.';
END;
GO

PRINT 'Creating APP_4_RECIPESUMMARY table';
GO

IF OBJECT_ID('dbo.com_5013_APP_4_RECIPESUMMARY', 'U') IS NULL
BEGIN
    CREATE TABLE dbo.com_5013_APP_4_RECIPESUMMARY (
        ID BIGINT NOT NULL,
        ITEM_ID BIGINT NULL,
        RM_ITEM_ID BIGINT NULL,
        DOUBLE_QUANTITY DECIMAL(16,4) NULL,
        SALES_TYPE VARCHAR(255) NULL,
        TRANSACTION_DATETIME VARCHAR(50) NULL,
        DATETIME__TRANSACTION_DATETIME DATE NULL,
        PAIR_ID BIGINT NULL,
        INT_EXTEND_1 INT NULL,
        INT_EXTEND_2 INT NULL,
        INT_EXTEND_3 INT NULL,
        STRING_EXTEND_1 VARCHAR(255) NULL,
        STRING_EXTEND_2 VARCHAR(255) NULL,
        STRING_EXTEND_3 VARCHAR(255) NULL,
        WBDELETED TINYINT NULL,
        UPDATE_TIMESTAMP BINARY(8) NULL,
        DOUBLE_COST DECIMAL(16,4) NULL,
        CONSTRAINT PK_com_5013_APP_4_RECIPESUMMARY PRIMARY KEY CLUSTERED (ID)
    );
    PRINT 'Table dbo.com_5013_APP_4_RECIPESUMMARY created.';
END
ELSE
BEGIN
    PRINT 'Table dbo.com_5013_APP_4_RECIPESUMMARY already exists.';
END;
GO

PRINT 'Creating APP_4_SALESQUANTITIES table';
GO

IF OBJECT_ID('dbo.com_5013_APP_4_SALESQUANTITIES', 'U') IS NULL
BEGIN
    CREATE TABLE dbo.com_5013_APP_4_SALESQUANTITIES (
        ID BIGINT NOT NULL,
        ITEM_ID VARCHAR(30) NULL,
        LOCATION_ID VARCHAR(100) NULL,
        DOUBLE_SOLD_QTY DECIMAL(16,4) NULL,
        LAST_UPDATE_DATE VARCHAR(30) NULL,
        SDAY INT NULL,
        SMONTH INT NULL,
        SYEAR INT NULL,
        SALES_DATE VARCHAR(14) NULL,
        DOUBLE_SOLD_AMOUNT DECIMAL(16,4) NULL,
        INT_EXTEND_1 INT NULL,
        INT_EXTEND_2 INT NULL,
        INT_EXTEND_3 INT NULL,
        STRING_EXTEND_1 VARCHAR(255) NULL,
        STRING_EXTEND_2 VARCHAR(255) NULL,
        STRING_EXTEND_3 VARCHAR(255) NULL,
        WBDELETED TINYINT NULL,
        UPDATE_TIMESTAMP BINARY(8) NULL,
        CONSTRAINT PK_com_5013_APP_4_SALESQUANTITIES PRIMARY KEY CLUSTERED (ID)
    );
    PRINT 'Table dbo.com_5013_APP_4_SALESQUANTITIES created.';
END
ELSE
BEGIN
    PRINT 'Table dbo.com_5013_APP_4_SALESQUANTITIES already exists.';
END;
GO

PRINT 'Creating APP_4_COMBOITEMPRICE table';
GO

IF OBJECT_ID('dbo.com_5013_APP_4_COMBOITEMPRICE', 'U') IS NULL
BEGIN
    CREATE TABLE dbo.com_5013_APP_4_COMBOITEMPRICE (
        ID BIGINT NOT NULL,
        COMBOITEMID BIGINT NULL,
        ITEMID BIGINT NULL,
        PRICE DECIMAL(16,4) NULL,
        WBDELETED TINYINT NULL,
        UPDATE_TIMESTAMP BINARY(8) NULL,
        CONSTRAINT PK_com_5013_APP_4_COMBOITEMPRICE PRIMARY KEY CLUSTERED (ID)
    );
    PRINT 'Table dbo.com_5013_APP_4_COMBOITEMPRICE created.';
END
ELSE
BEGIN
    PRINT 'Table dbo.com_5013_APP_4_COMBOITEMPRICE already exists.';
END;
GO

PRINT 'Product Mix source tables migration complete.';
GO
