-- Migration: Create APP_4_ORDER and APP_4_ORDERITEM tables for order-level replication

PRINT 'Creating APP_4_ORDER table';
GO

IF OBJECT_ID('dbo.com_5013_APP_4_ORDER', 'U') IS NULL
BEGIN
    CREATE TABLE dbo.com_5013_APP_4_ORDER (
        ID BIGINT NOT NULL,
        ORDER_ID VARCHAR(50) NULL,
        ORDER_DATE VARCHAR(50) NULL,
        DATETIME__ORDER_DATE DATE NULL,
        ORDER_TIME VARCHAR(50) NULL,
        DOUBLE_TOTAL_AMOUNT DECIMAL(16,4) NULL,
        RECIPIENT VARCHAR(255) NULL,
        CUSTOMERID VARCHAR(50) NULL,
        TIME VARCHAR(50) NULL,
        DOUBLE_PAID_AMOUNT DECIMAL(16,4) NULL,
        DOUBLE_BALANCE_AMOUNT DECIMAL(16,4) NULL,
        CASHIER VARCHAR(255) NULL,
        BOOL_IS_RESERVATION TINYINT NULL,
        ORDER_STATUS VARCHAR(255) NULL,
        ORDER_PERSON VARCHAR(255) NULL,
        PAYMENT_STATUS VARCHAR(255) NULL,
        LOCATION_ID VARCHAR(255) NULL,
        DOUBLE_DISCOUNT_PERCENTAGE DECIMAL(16,4) NULL,
        DOUBLE_TAX_PERCENTAGE DECIMAL(16,4) NULL,
        ORDER_NO VARCHAR(255) NULL,
        SALES_NO VARCHAR(50) NULL,
        PAX_NO VARCHAR(255) NULL,
        ORDER_TYPE VARCHAR(255) NULL,
        SITEID VARCHAR(50) NULL,
        DOUBLE_COST DECIMAL(16,4) NULL,
        DOUBLE_PROFIT DECIMAL(16,4) NULL,
        DOUBLE_ROUNDINGAMOUNT DECIMAL(16,4) NULL,
        ORDER_REMARK VARCHAR(255) NULL,
        CANCEL_BY VARCHAR(255) NULL,
        CANCEL_REMARK VARCHAR(255) NULL,
        CANCEL_DATE VARCHAR(255) NULL,
        DATETIME__CANCEL_DATE DATE NULL,
        CANCEL_TIME VARCHAR(255) NULL,
        CANCEL_LOCATION_ID VARCHAR(255) NULL,
        DOUBLE_NET_AMOUNT DECIMAL(16,4) NULL,
        DECLARATIONSESSIONID VARCHAR(50) NULL,
        EODLOGID VARCHAR(50) NULL,
        REF_ORDER_ID VARCHAR(50) NULL,
        DOUBLE_MGST_TAX_AMOUNT DECIMAL(16,4) NULL,
        BUSINESS_DATE VARCHAR(255) NULL,
        DATETIME__BUSINESS_DATE DATE NULL,
        BOOL_ISBILLPRINTED TINYINT NULL,
        INT_PRINTBILLCOUNT INT NULL,
        DOUBLE_SERVICECHARGE_AMOUNT DECIMAL(16,4) NULL,
        EXTERNAL_REF_ID VARCHAR(50) NULL,
        RESERVATION_DATE VARCHAR(100) NULL,
        RESERVATION_TIME VARCHAR(100) NULL,
        CUSTOMERNAME VARCHAR(100) NULL,
        MOBILE_NO VARCHAR(100) NULL,
        ORDER_SOURCE VARCHAR(255) NULL,
        INT_EXTEND_1 INT NULL,
        INT_EXTEND_2 INT NULL,
        INT_EXTEND_3 INT NULL,
        STRING_EXTEND_1 VARCHAR(255) NULL,
        STRING_EXTEND_2 VARCHAR(255) NULL,
        STRING_EXTEND_3 VARCHAR(255) NULL,
        WBDELETED TINYINT NULL,
        UPDATE_TIMESTAMP BINARY(8) NULL,
        ORDER_GUID VARCHAR(255) NULL,
        DELIVERY_TYPE VARCHAR(255) NULL,
        DATETIME_RESERVATIONDATE DATETIME NULL,
        CONSTRAINT PK_com_5013_APP_4_ORDER PRIMARY KEY CLUSTERED (ID)
    );
    PRINT 'Table dbo.com_5013_APP_4_ORDER created.';
END
ELSE
BEGIN
    PRINT 'Table dbo.com_5013_APP_4_ORDER already exists.';
END;
GO

PRINT 'Creating APP_4_ORDERITEM table';
GO

IF OBJECT_ID('dbo.com_5013_APP_4_ORDERITEM', 'U') IS NULL
BEGIN
    CREATE TABLE dbo.com_5013_APP_4_ORDERITEM (
        ID BIGINT NOT NULL,
        ITEM_ID VARCHAR(50) NULL,
        ITEM_NAME VARCHAR(255) NULL,
        ITEM_TYPE VARCHAR(255) NULL,
        MODEL VARCHAR(255) NULL,
        DESCRIPTION VARCHAR(255) NULL,
        DOUBLE_PRICE DECIMAL(16,4) NULL,
        DOUBLE_ENTER_PRICE DECIMAL(16,4) NULL,
        ORDER_ID VARCHAR(50) NULL,
        QUANTITY DECIMAL(16,4) NULL,
        DOUBLE_ORDER_PRICE DECIMAL(16,4) NULL,
        DOUBLE_PROFIT DECIMAL(16,4) NULL,
        DOUBLE_DISCOUNT_PERCENTAGE DECIMAL(16,4) NULL,
        INSTORE_LOCATION VARCHAR(255) NULL,
        ORDER_DATE VARCHAR(50) NULL,
        ORDER_TIME VARCHAR(50) NULL,
        ITEM_REMARK VARCHAR(255) NULL,
        ORDERITEM_CODE VARCHAR(255) NULL,
        DOUBLE_GST_PERCENTAGE DECIMAL(16,4) NULL,
        DOUBLE_GST_AMOUNT DECIMAL(16,4) NULL,
        BOOL_IS_UNIQUE_ITEM TINYINT NULL,
        UNIQUECODE VARCHAR(255) NULL,
        BOOL_ISPACKAGE TINYINT NULL,
        BOOL_ISSERVICE TINYINT NULL,
        BOOL_IS_PREPACK TINYINT NULL,
        PCID VARCHAR(255) NULL,
        ITEMINDEX INT NULL,
        CASHIER VARCHAR(255) NULL,
        LOCATION_ID VARCHAR(255) NULL,
        ITEM_CATEGORY VARCHAR(255) NULL,
        ORDERITEM_REMARK VARCHAR(255) NULL,
        BOOL_ISPRINT TINYINT NULL,
        ORDER_PERSON VARCHAR(255) NULL,
        ALT_LOOKUP VARCHAR(255) NULL,
        DECLARATIONSESSIONID VARCHAR(50) NULL,
        EODLOGID VARCHAR(50) NULL,
        REF_SALESITEM_ID VARCHAR(50) NULL,
        PROMO_GROUP VARCHAR(255) NULL,
        MGST_TAX_CODE VARCHAR(50) NULL,
        DOUBLE_MGST_TAX_PERCENTAGE DECIMAL(16,4) NULL,
        DOUBLE_MGST_TAX_AMOUNT DECIMAL(16,4) NULL,
        PROMOGUID VARCHAR(255) NULL,
        PROMOIGNORE TINYINT NULL,
        BOOL_IS_INCLUSIVE_MGST TINYINT NULL,
        ORDERITEM_ORDERTYPE VARCHAR(255) NULL,
        DOUBLE_SERVICECHARGE_PERCENTAGE DECIMAL(16,4) NULL,
        DISCOUNT_REMARK VARCHAR(255) NULL,
        BOOL_DISCOUNTINCLUDESUBITEM TINYINT NULL,
        ORDERITEMSAVED_DATETIME VARCHAR(50) NULL,
        BOOL_PRINTSTATUS TINYINT NULL,
        DOUBLE_SUB_TOTAL VARCHAR(255) NULL,
        DOUBLE_TOTAL_TAX_AMOUNT VARCHAR(255) NULL,
        ORDERTERMINALID VARCHAR(255) NULL,
        ORDER_SOURCE VARCHAR(255) NULL,
        INT_EXTEND_1 INT NULL,
        INT_EXTEND_2 INT NULL,
        INT_EXTEND_3 INT NULL,
        STRING_EXTEND_1 VARCHAR(255) NULL,
        STRING_EXTEND_2 VARCHAR(255) NULL,
        STRING_EXTEND_3 VARCHAR(255) NULL,
        WBDELETED TINYINT NULL,
        UPDATE_TIMESTAMP BINARY(8) NULL,
        DELIVERY_TYPE VARCHAR(255) NULL,
        CONSTRAINT PK_com_5013_APP_4_ORDERITEM PRIMARY KEY CLUSTERED (ID)
    );
    PRINT 'Table dbo.com_5013_APP_4_ORDERITEM created.';
END
ELSE
BEGIN
    PRINT 'Table dbo.com_5013_APP_4_ORDERITEM already exists.';
END;
GO

PRINT 'Order tables migration complete.';
GO
