-- Migration: Create menu tables for Product Mix
-- Tables: APP_4_MENUPROFILE, APP_4_MENUPROFILEMAPPING, APP_4_MENUMAINCATEGORY,
--         APP_4_MENUSUBCATEGORY, APP_4_MENUITEMMODIFIER, APP_4_MENUITEMOUTOFSTOCK

PRINT 'Creating APP_4_MENUPROFILE table';
GO
IF OBJECT_ID('dbo.com_5013_APP_4_MENUPROFILE', 'U') IS NULL
BEGIN
    CREATE TABLE dbo.com_5013_APP_4_MENUPROFILE (
        ID BIGINT NOT NULL,
        PROFILENAME VARCHAR(255) NULL,
        DATE_CREATED VARCHAR(255) NULL,
        BOOL_ISACTIVATED TINYINT NULL,
        LOCATIONID VARCHAR(255) NULL,
        REMARK VARCHAR(MAX) NULL,
        DATESTART VARCHAR(25) NULL,
        DATEEND VARCHAR(25) NULL,
        TIMESTART VARCHAR(25) NULL,
        TIMEEND VARCHAR(25) NULL,
        BOOL_MONDAY TINYINT NULL,
        BOOL_TUESDAY TINYINT NULL,
        BOOL_WEDNESDAY TINYINT NULL,
        BOOL_THURSDAY TINYINT NULL,
        BOOL_FRIDAY TINYINT NULL,
        BOOL_SATURDAY TINYINT NULL,
        BOOL_SUNDAY TINYINT NULL,
        BOOL_WEEK1 TINYINT NULL,
        BOOL_WEEK2 TINYINT NULL,
        BOOL_WEEK3 TINYINT NULL,
        BOOL_WEEK4 TINYINT NULL,
        BOOL_WEEK5 TINYINT NULL,
        INT_TIME_PRIORITY INT NULL,
        ROWLOCKING VARCHAR(25) NULL,
        INT_EXTEND_1 BIGINT NULL,
        INT_EXTEND_2 INT NULL,
        INT_EXTEND_3 INT NULL,
        STRING_EXTEND_1 VARCHAR(255) NULL,
        STRING_EXTEND_2 VARCHAR(255) NULL,
        STRING_EXTEND_3 VARCHAR(255) NULL,
        WBDELETED TINYINT NULL,
        UPDATE_TIMESTAMP VARBINARY(8) NULL,
        IS_ENABLE_BRANCHASSORTMENT TINYINT NULL,
        DATETIME_MODIFIED DATETIME NULL
    );
    PRINT 'Table dbo.com_5013_APP_4_MENUPROFILE created.';
END
ELSE
BEGIN
    PRINT 'Table dbo.com_5013_APP_4_MENUPROFILE already exists.';
END;
GO

PRINT 'Creating APP_4_MENUPROFILEMAPPING table';
GO
IF OBJECT_ID('dbo.com_5013_APP_4_MENUPROFILEMAPPING', 'U') IS NULL
BEGIN
    CREATE TABLE dbo.com_5013_APP_4_MENUPROFILEMAPPING (
        ID BIGINT NOT NULL,
        MENUPROFILEID INT NULL,
        MENUMAINCATEGORYID INT NULL,
        MENUSUBCATEGORYID INT NULL,
        MENUITEMMODIFIERID INT NULL,
        INT_EXTEND_1 INT NULL,
        INT_EXTEND_2 INT NULL,
        INT_EXTEND_3 INT NULL,
        STRING_EXTEND_1 VARCHAR(255) NULL,
        STRING_EXTEND_2 VARCHAR(255) NULL,
        STRING_EXTEND_3 VARCHAR(255) NULL,
        WBDELETED TINYINT NULL,
        UPDATE_TIMESTAMP VARBINARY(8) NULL
    );
    PRINT 'Table dbo.com_5013_APP_4_MENUPROFILEMAPPING created.';
END
ELSE
BEGIN
    PRINT 'Table dbo.com_5013_APP_4_MENUPROFILEMAPPING already exists.';
END;
GO

PRINT 'Creating APP_4_MENUMAINCATEGORY table';
GO
IF OBJECT_ID('dbo.com_5013_APP_4_MENUMAINCATEGORY', 'U') IS NULL
BEGIN
    CREATE TABLE dbo.com_5013_APP_4_MENUMAINCATEGORY (
        ID BIGINT NOT NULL,
        CATEGORYNAME VARCHAR(255) NULL,
        INT_ORDER INT NULL,
        COLOR_HEX VARCHAR(255) NULL,
        LOCATIONID VARCHAR(100) NULL,
        BINARYKEY VARCHAR(100) NULL,
        INT_PAGING INT NULL,
        INT_SUBMENU_COLUMN INT NULL,
        INT_SUBMENU_ROW INT NULL,
        INT_EXTEND_1 INT NULL,
        INT_EXTEND_2 INT NULL,
        INT_EXTEND_3 INT NULL,
        STRING_EXTEND_1 VARCHAR(255) NULL,
        STRING_EXTEND_2 VARCHAR(255) NULL,
        STRING_EXTEND_3 VARCHAR(255) NULL,
        WBDELETED TINYINT NULL,
        UPDATE_TIMESTAMP VARBINARY(8) NULL,
        INT_MAX INT NULL,
        INT_MIN INT NULL
    );
    PRINT 'Table dbo.com_5013_APP_4_MENUMAINCATEGORY created.';
END
ELSE
BEGIN
    PRINT 'Table dbo.com_5013_APP_4_MENUMAINCATEGORY already exists.';
END;
GO

PRINT 'Creating APP_4_MENUSUBCATEGORY table';
GO
IF OBJECT_ID('dbo.com_5013_APP_4_MENUSUBCATEGORY', 'U') IS NULL
BEGIN
    CREATE TABLE dbo.com_5013_APP_4_MENUSUBCATEGORY (
        ID BIGINT NOT NULL,
        SUBITEMID VARCHAR(100) NULL,
        INT_ORDER INT NULL,
        COLOR_HEX VARCHAR(255) NULL,
        LOCATIONID VARCHAR(100) NULL,
        CATEGORY VARCHAR(255) NULL,
        BINARYKEY VARCHAR(100) NULL,
        GROUPMATCH VARCHAR(254) NULL,
        GROUPVALUE VARCHAR(254) NULL,
        BOOL_ISMODIFERNEEDED TINYINT NULL,
        INT_PAGING INT NULL,
        INT_EXTEND_1 INT NULL,
        INT_EXTEND_2 INT NULL,
        INT_EXTEND_3 INT NULL,
        STRING_EXTEND_1 VARCHAR(255) NULL,
        STRING_EXTEND_2 VARCHAR(255) NULL,
        STRING_EXTEND_3 VARCHAR(255) NULL,
        WBDELETED TINYINT NULL,
        UPDATE_TIMESTAMP VARBINARY(8) NULL,
        DISPLAYNAME VARCHAR(255) NULL,
        BOOL_ISSORTBYALPHABETIC TINYINT NULL,
        BOOL_ISCOMBO TINYINT NULL
    );
    PRINT 'Table dbo.com_5013_APP_4_MENUSUBCATEGORY created.';
END
ELSE
BEGIN
    PRINT 'Table dbo.com_5013_APP_4_MENUSUBCATEGORY already exists.';
END;
GO

PRINT 'Creating APP_4_MENUITEMMODIFIER table';
GO
IF OBJECT_ID('dbo.com_5013_APP_4_MENUITEMMODIFIER', 'U') IS NULL
BEGIN
    CREATE TABLE dbo.com_5013_APP_4_MENUITEMMODIFIER (
        ID BIGINT NOT NULL,
        ITEMMODIFIERID VARCHAR(100) NULL,
        INT_ORDER INT NULL,
        COLOR_HEX VARCHAR(255) NULL,
        SUBITEMID VARCHAR(100) NULL,
        LOCATIONID VARCHAR(100) NULL,
        BINARYKEY VARCHAR(100) NULL,
        ROWINDEX INT NULL,
        COLUMNINDEX INT NULL,
        GROUPMATCH VARCHAR(254) NULL,
        GROUPFILTERING VARCHAR(MAX) NULL,
        HEADERLABEL VARCHAR(254) NULL,
        DEFAULTINDEX VARCHAR(254) NULL,
        BOOL_ISDYNAMICQUERY TINYINT NULL,
        BOOL_ISCOMPULSORY TINYINT NULL,
        BOOL_ISTOGGLECHECK TINYINT NULL,
        INT_PAGING INT NULL,
        INT_EXTEND_1 INT NULL,
        INT_EXTEND_2 INT NULL,
        INT_EXTEND_3 INT NULL,
        STRING_EXTEND_1 VARCHAR(255) NULL,
        STRING_EXTEND_2 VARCHAR(255) NULL,
        STRING_EXTEND_3 VARCHAR(255) NULL,
        WBDELETED TINYINT NULL,
        UPDATE_TIMESTAMP VARBINARY(8) NULL,
        LOWESTQTY INT NULL,
        HIGHESTQTY INT NULL
    );
    PRINT 'Table dbo.com_5013_APP_4_MENUITEMMODIFIER created.';
END
ELSE
BEGIN
    PRINT 'Table dbo.com_5013_APP_4_MENUITEMMODIFIER already exists.';
END;
GO

PRINT 'Creating APP_4_MENUITEMOUTOFSTOCK table';
GO
IF OBJECT_ID('dbo.com_5013_APP_4_MENUITEMOUTOFSTOCK', 'U') IS NULL
BEGIN
    CREATE TABLE dbo.com_5013_APP_4_MENUITEMOUTOFSTOCK (
        ID BIGINT NOT NULL,
        ITEM_ID VARCHAR(255) NULL,
        ITEM_CODE VARCHAR(255) NULL,
        ITEM_NAME VARCHAR(255) NULL,
        ITEM_CATEGORY VARCHAR(255) NULL,
        LOCATIONID VARCHAR(255) NULL,
        DATESTART VARCHAR(50) NULL,
        DATETIME__DATESTART DATE NULL,
        DATEEND VARCHAR(50) NULL,
        DATETIME__DATEEND DATE NULL,
        TIMESTART VARCHAR(50) NULL,
        TIMEEND VARCHAR(50) NULL,
        BOOL_MONDAY TINYINT NULL,
        BOOL_TUESDAY TINYINT NULL,
        BOOL_WEDNESDAY TINYINT NULL,
        BOOL_THURSDAY TINYINT NULL,
        BOOL_FRIDAY TINYINT NULL,
        BOOL_SATURDAY TINYINT NULL,
        BOOL_SUNDAY TINYINT NULL,
        BOOL_WEEK1 TINYINT NULL,
        BOOL_WEEK2 TINYINT NULL,
        BOOL_WEEK3 TINYINT NULL,
        BOOL_WEEK4 TINYINT NULL,
        BOOL_WEEK5 TINYINT NULL,
        ROWLOCKING VARCHAR(25) NULL,
        INT_EXTEND_1 INT NULL,
        INT_EXTEND_2 INT NULL,
        INT_EXTEND_3 INT NULL,
        STRING_EXTEND_1 VARCHAR(255) NULL,
        STRING_EXTEND_2 VARCHAR(255) NULL,
        STRING_EXTEND_3 VARCHAR(255) NULL,
        WBDELETED TINYINT NULL,
        UPDATE_TIMESTAMP VARBINARY(8) NULL,
        ORDER_SOURCE VARCHAR(255) NULL,
        TOTALQTY DECIMAL(38,20) NULL,
        DOUBLE_QTY DECIMAL(38,20) NULL,
        SALES_TYPE VARCHAR(14) NULL
    );
    PRINT 'Table dbo.com_5013_APP_4_MENUITEMOUTOFSTOCK created.';
END
ELSE
BEGIN
    PRINT 'Table dbo.com_5013_APP_4_MENUITEMOUTOFSTOCK already exists.';
END;
GO

PRINT 'Menu tables migration complete.';
GO