-- Migration: Create menu availability + price log tables
-- Tables: APP_4_MENUITEMAVAILABILITYCONFIG, APP_4_PRICELOG

PRINT 'Creating APP_4_MENUITEMAVAILABILITYCONFIG table';
GO
IF OBJECT_ID('dbo.com_5013_APP_4_MENUITEMAVAILABILITYCONFIG', 'U') IS NULL
BEGIN
    CREATE TABLE dbo.com_5013_APP_4_MENUITEMAVAILABILITYCONFIG (
        ID BIGINT NOT NULL,
        ITEM_ID BIGINT NULL,
        BOOL_MONDAY TINYINT NULL,
        BOOL_TUESDAY TINYINT NULL,
        BOOL_WEDNESDAY TINYINT NULL,
        BOOL_THURSDAY TINYINT NULL,
        BOOL_FRIDAY TINYINT NULL,
        BOOL_SATURDAY TINYINT NULL,
        BOOL_SUNDAY TINYINT NULL,
        BOOL_IS_ACTIVE TINYINT NULL,
        BOOL_IS_INACTIVE TINYINT NULL,
        DATETIMEUTC_DATEFROM DATETIME NULL,
        DATETIMEUTC_DATETO DATETIME NULL,
        WBDELETED TINYINT NULL,
        UPDATE_TIMESTAMP VARBINARY(8) NULL
    );
    PRINT 'Table dbo.com_5013_APP_4_MENUITEMAVAILABILITYCONFIG created.';
END
ELSE
BEGIN
    PRINT 'Table dbo.com_5013_APP_4_MENUITEMAVAILABILITYCONFIG already exists.';
END;
GO

PRINT 'Creating APP_4_PRICELOG table';
GO
IF OBJECT_ID('dbo.com_5013_APP_4_PRICELOG', 'U') IS NULL
BEGIN
    CREATE TABLE dbo.com_5013_APP_4_PRICELOG (
        ID BIGINT NOT NULL,
        ITEM_ID VARCHAR(50) NULL,
        LOCATION_ID VARCHAR(255) NULL,
        MATRIX_BARCODE VARCHAR(255) NULL,
        VALUE_X VARCHAR(255) NULL,
        VALUE_Y VARCHAR(255) NULL,
        DATETIME VARCHAR(50) NULL,
        DOUBLE_PRICE_VALUE DECIMAL(16,4) NULL,
        PRICE_SCHEME_ENUM VARCHAR(255) NULL,
        DATETIME__DATETIME DATE NULL,
        DOUBLE_PREV_PRICE_VALUE DECIMAL(16,4) NULL,
        CREATED_BY VARCHAR(255) NULL,
        DOUBLE_PREV_PRICE_1 DECIMAL(16,4) NULL,
        DOUBLE_PREV_PRICE_2 DECIMAL(16,4) NULL,
        DOUBLE_PREV_PRICE_3 DECIMAL(16,4) NULL,
        DOUBLE_PREV_PRICE_4 DECIMAL(16,4) NULL,
        DOUBLE_PREV_PRICE_5 DECIMAL(16,4) NULL,
        DOUBLE_PREV_PRICE_6 DECIMAL(16,4) NULL,
        DOUBLE_PREV_PRICE_7 DECIMAL(16,4) NULL,
        DOUBLE_PREV_COST DECIMAL(16,4) NULL,
        DOUBLE_POST_PRICE_1 DECIMAL(16,4) NULL,
        DOUBLE_POST_PRICE_2 DECIMAL(16,4) NULL,
        DOUBLE_POST_PRICE_3 DECIMAL(16,4) NULL,
        DOUBLE_POST_PRICE_4 DECIMAL(16,4) NULL,
        DOUBLE_POST_PRICE_5 DECIMAL(16,4) NULL,
        DOUBLE_POST_PRICE_6 DECIMAL(16,4) NULL,
        DOUBLE_POST_PRICE_7 DECIMAL(16,4) NULL,
        DOUBLE_POST_COST DECIMAL(16,4) NULL,
        INT_EXTEND_1 INT NULL,
        INT_EXTEND_2 INT NULL,
        INT_EXTEND_3 INT NULL,
        STRING_EXTEND_1 VARCHAR(255) NULL,
        STRING_EXTEND_2 VARCHAR(255) NULL,
        STRING_EXTEND_3 VARCHAR(255) NULL,
        WBDELETED TINYINT NULL,
        UPDATE_TIMESTAMP VARBINARY(8) NULL,
        DOUBLE_PREV_FOREIGN_COST DECIMAL(16,4) NULL,
        DOUBLE_POST_FOREIGN_COST DECIMAL(16,4) NULL
    );
    PRINT 'Table dbo.com_5013_APP_4_PRICELOG created.';
END
ELSE
BEGIN
    PRINT 'Table dbo.com_5013_APP_4_PRICELOG already exists.';
END;
GO

PRINT 'Menu availability + price log tables migration complete.';
GO
